### ISSUE TITLE
Design and develop event hub client

### ISSUE THREAD

**Issue by tishan89** [wso2/apim-analytics-publisher#8]
**Description**
Design and develop client code to connect to event hub and publish the given analytics events in a resilient manner. Following functional and non-functional requirements should be met
* Should publish events to EventHub in a resilient and fail safe manner. At least once QoS guarantee should be achieved
* Should accepts events though a non-blocking bounded queue to have minimal impact on the GW
* Separate parallel workers should consume the queue and publish to Event Hub using Event Hub Java SDK and Azure Schema Registry
* In an event of connection loss, once the queue is full should drop any newly arriving events till connection is re-established and queue is flushed.

**Sub Tasks**

- [x] [Improve metric reporter interface](https://github.com/wso2/apim-analytics-publisher/issues/16)
- [x] [Implement queuing async publisher](https://github.com/wso2/apim-analytics-publisher/issues/17)
- [x] [Add error handling](https://github.com/wso2/apim-analytics-publisher/issues/30)
- [x] [Add schema validation](https://github.com/wso2/apim-analytics-publisher/issues/24)

This will be tracked as a sub task in [this](https://github.com/wso2/apim-analytics-publisher/issues/9) issue.
