### ISSUE TITLE
Analytics Publisher implementation for APIM4

### ISSUE THREAD

**Issue by tishan89** [wso2/apim-analytics-publisher#9]
**Description**
This issue is to track the progress of analytics publishing effort of APIM 4.0.0. Below is the high-level design diagram which will be updated in due course.

![image](https://user-images.githubusercontent.com/1623470/105457866-8b3c1400-5cad-11eb-86ec-e620af93502b.png)

Below are the subtasks related to this high-level objective. 

- [x] [Design and develop common metric reporter interface to accept metrics](https://github.com/wso2/apim-analytics-publisher/issues/7)
- [x] [Design and develop client to Auth API](https://github.com/wso2/apim-analytics-publisher/issues/18)
- [x] [Design and develop resilient event hub client](https://github.com/wso2/apim-analytics-publisher/issues/8) 
- [x] [Design and develop synapse instrumentation](https://github.com/wso2-enterprise/choreo-analytics-apim/issues/90)
- [x] [Design and develop Auth API](https://github.com/wso2/apim-analytics-publisher/issues/10)

Publishing even schema can be found [here](https://github.com/wso2-enterprise/choreo-analytics-apim/issues/89)

**Comment by ruks** [comment]
https://github.com/wso2-enterprise/choreo-analytics-apim/issues/90
